name: "Lint code, Black"

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Set-up Python env
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'poetry'

      - name: Restore dependencies
        run: poetry install

      - name: Run Lint - Black
        run: poetry run black .

